### ISSUE TITLE
Missing Homebrew Installer

### ISSUE THREAD

**Issue by albertomurillo** [ediardo/kmdr-cli#10]
Homebrew is a popular package manager to install cli tools on OSX and there is no formula for `kmdr`.

An incomplete formula (missing tests) can be found [here](https://github.com/albertomurillo/homebrew-tap/blob/master/Formula/kmdr.rb) but I will not maintain it.

It would be cool to be able to install kmdr with
```
brew install ediardo/kmdr/kmdr
```

For this you can copy the sample formula to 

`github.com/ediardo/homebrew-kmdr/Formula/kmdr.rb`

For more info refer to https://docs.brew.sh/Taps

**Comment by ediardo** [comment]
Hi @albertomurillo, thanks a lot for the contribution! I'll check it out as soons as I have my hands on a mac.

**Comment by ediardo** [comment]
It works! I cloned your repo, renamed as `homebrew-tap` and finally ran the command `brew install ediardo/kmdr/kmdr`.

**Comment by ediardo** [comment]
PR with your Formula was submitted to the `homebrew-core` project. Still waiting for review.

https://github.com/Homebrew/homebrew-core/pull/44376

**Comment by ediardo** [comment]
Created a custom homebrew tap at https://github.com/kommandr/homebrew-tap
