### ISSUE TITLE
Cursor is weird

### ISSUE THREAD

**Issue by kud** [ediardo/kmdr-cli#15]
**Describe the bug**
The cursor moves a weird way, like laggy and got a space between the character and the cursor itself

**Expected behavior**
Should work like other commands / like my shell

**Screenshots**
![Kapture 2019-09-11 at 10 06 09](https://user-images.githubusercontent.com/655838/64679331-d3251700-d47b-11e9-9392-b0d974302a1b.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version: 0.1.29

**Comment by ediardo** [comment]
HI @kud, thanks for creating this issue. I'm able to reproduce the bug on multiple terminals and it's very annoying.

**Comment by ediardo** [comment]
Fixed in version `0.1.33`.
