### ISSUE TITLE
kmdr does not work behind a proxy

### ISSUE THREAD

**Issue by ediardo** [ediardo/kmdr-cli#3]
Some of the errors:

```
kmdr e                 
👋 Hi, welcome to kmdr!
This CLI program explains shell commands right on your terminal!

💡 Enter your command:  ls
Error: Client network socket disconnected before secure TLS connection was established
```

**Comment by ediardo** [comment]
I tried some solutions but none of them worked. `http_proxy` and `https_proxy `were set as environment variables and `axios` picked them up but I still got the same error again.

**Comment by ajoyac** [comment]
I created a work around due the long issue with axxios to be proxy aware

**Comment by ediardo** [comment]
> I created a work around due the long issue with axxios to be proxy aware

Cool. I'll check it out :)
