### ISSUE TITLE
Feature request: example commands

### ISSUE THREAD

**Issue by OskarAhl** [ediardo/kmdr-cli#36]
A simple example for each command would be super nice 🙏

**Comment by ediardo** [comment]
Hi @OskarAhl,  What programs would you like to see examples of? We are rolling out a new version very soon and covering some examples for `rm`, `mv`, `tar`, `cp`, `npm`, `git`, `find` and `ps`. More suggestions are welcome :)

**Comment by ediardo** [comment]
@OskarAhl: you can now upgrade kmdr-cli to version 0.3. It includes example commands for the 10 most popular programs in our platform. Get the latest version with `npm install kmdr@latest --global` or `yarn global add kmdr@latest`.

Some screenshots of v0.3🔥

![v0 3-ls](https://user-images.githubusercontent.com/1195596/68688844-50c0de00-0524-11ea-9deb-5b2b1daa0eb1.png)
![v0 3-git-commit](https://user-images.githubusercontent.com/1195596/68688848-528aa180-0524-11ea-8c51-3a41731da222.png)
![v0 3 (2)](https://user-images.githubusercontent.com/1195596/68688879-60402700-0524-11ea-87ac-2b3dee00483c.png)

**Comment by ediardo** [comment]
I'm closing this issue. Please create a new one if you want examples for some specific programs :).

**Comment by OskarAhl** [comment]
@ediardo wow that is awesome, thank you!
