### ISSUE TITLE
kmdr not working due to /usr/bin/env

### ISSUE THREAD

**Issue by DanielTimLee** [ediardo/kmdr-cli#38]
**Describe the bug**
kmdr not working due to /usr/bin/env

**To Reproduce**

1. install with npm@latest
2. execute kmdr
3. Error

```bash
$ kmdr
/usr/bin/env: ‘node --no-deprecation’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
$ env --version
env (GNU coreutils) 8.31
$ uname -a
Linux A 5.4.0-1-MANJARO #1 SMP PREEMPT Mon Nov 11 19:40:28 UTC 2019 x86_64 GNU/Linux
$ env node --no-deprecation
Welcome to Node.js v12.13.0.
Type ".help" for more information.
> 
```

**Desktop (please complete the following information):**
 - OS: Manjaro 18.1.3

**Comment by DanielTimLee** [comment]
Seems shebang with argument doesn't work in Linux.
(Guess everyone running on a BSD(mac)?)

https://unix.stackexchange.com/questions/63979/shebang-line-with-usr-bin-env-command-argument-fails-on-linux

**Comment by DanielTimLee** [comment]
https://github.com/ediardo/kmdr-cli/blob/7b4708b7045d075bd53d9713d79394ba2b26b3d7/src/bin.ts#L1

This will work on coreutils 8.30, an -S option, but not sure BSD env got this option. 
And also other Linux distro might have lower version of coreutils than 8.30.

```sh
#!/usr/bin/env -S node --no-deprecation
```

```sh
$ env --help
Usage: env [OPTION]... [-] [NAME=VALUE]... [COMMAND [ARG]...]
Set each NAME to VALUE in the environment and run COMMAND.

Mandatory arguments to long options are mandatory for short options too.
  -i, --ignore-environment  start with an empty environment
  -0, --null           end each output line with NUL, not newline
  -u, --unset=NAME     remove variable from the environment
  -C, --chdir=DIR      change working directory to DIR
  -S, --split-string=S  process and split S into separate arguments;
                        used to pass multiple arguments on shebang lines
```

**Comment by ediardo** [comment]
Hi @DanielTimLee , thanks for the detailed information and the PR #39  :)

I saw this error while running kmdr-cli in a container but couldn't reproduce the bug. There are two possible workarounds for this problem:

- Pass the `-S` flag to `env`. Proposed by @DanielTimLee:
  ```
  #!/usr/bin/env -S node --no-deprecation
  ```
- Remove the `--no-deprecation` flag:
  ```
  #!/usr/bin/env node
  ```

**Comment by ediardo** [comment]
I'll remove the `--no-deprecation` flag for now
