### ISSUE TITLE
Sharing does not work from installed kmdr-cli

### ISSUE THREAD

**Issue by siduxdevil** [ediardo/kmdr-cli#52]
**Describe the bug**
Sharing does not work from installed kmdr-cli
**To Reproduce**
1. Go to your terminal
2. Enter 'kmdr e', hit enter, type your command and hit enter again
3. Scroll down to the end of the explanation, use your arrow key to select 'Share this explain session' and hit enter again. You are then prompted to put in a name for the session to save. At this point it does not matter if you put in a name or not. After hitting enter for a last time, you are presented a link that is clickable to open in the browser. This runs into a timeout on Chrome and Firefox for me. It makes no difference if I click the link or copy&paste into the browser.

**Expected behavior**
I expect the link to open up in the browser.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian Sid
 - Browser  Firefox 73 and Chrome 79
kmdr-cli 0.4.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ediardo** [comment]
Hi @siduxdevil , thanks for the report. 

I couldn't reproduce the bug in version 0.4.3. I created two command explanations [0] using the latest version and the URLs did open on my browser. It could be that the deployment goes to sleep after some inactive time

Please try to open these urls and check if it works. Your explanation sessions should work too.

[0] - https://explain.kmdr.sh/s/c75be660-51e9-11ea-9d47-a942542b7054, https://explain.kmdr.sh/s/c75be660-51e9-11ea-9d47-a942542b7054
